module.exports = {
    keyMap: {
        dn: 'display: none',
        di: 'display: inline',
        dib: 'display: inline-block',
        db: 'display: block',
        dt: 'display: table',
        dtc: 'display: table-cell',
        m: 'margin: ',
        ml: 'margin-left: ',
        mt: 'margin-top: ',
        mr: 'margin-right: ',
        mb: 'margin-bottom: ',
        ma: 'margin: auto',
        mla: 'margin-left: auto',
        mra: 'margin-right: auto',
        p: 'padding: ',
        pl: 'padding-left: ',
        pt: 'padding-top: ',
        pr: 'padding-right: ',
        pb: 'padding-bottom: ',
        l: 'float: left',
        r: 'float: right',
        bg: 'background: ',
        bgc: 'background-color: ',
        bgi: 'background-image: ',
        bgr: 'background-repeat: ',
        bgp: 'background-position: ',
        bgs: 'background-size: ',
        bgo: 'background-origin: ',
        c: 'color: ',
        bd: 'border: ',
        bdl: 'border-left: ',
        bdr: 'border-right: ',
        bdt: 'border-top: ',
        bdb: 'border-bottom: ',
        bds: 'border-style: ',
        bdw: 'border-width: ',
        bdc: 'border-color: ',
        br: 'border-radius: ',
        bbb: 'box-sizing: border-box',
        o: 'outline: ',
        f: 'font-size: ',
        ff: 'font-family: ',
        fs: 'font-style: ',
        fw: 'font-weight: ',
        b: 'font-weight: bold',
        i: 'font-style: italic',
        n: 'font-weight: normal; font-style: normal',
        tdl: 'text-decoration: underline',
        tdn: 'text-decoration: none',
        tc: 'text-align: center',
        tl: 'text-align: left',
        tr: 'text-align: right',
        tj: 'text-align: justify',
        ti: 'text-indent: ',
        cl: 'clear: both',
        abs: 'position: absolute',
        rel: 'position: relative',
        fix: 'position: fixed',
        op: 'opacity: ',
        z: 'zoom: ',
        zx: 'z-index: ',
        h: 'height: ',
        w: 'width: ',
        minw: 'min-width: ',
        maxw: 'max-width: ',
        minh: 'min-height: ',
        maxh: 'max-height: ',
        lh: 'line-height: ',
        v: 'vertical-align: ',
        vt: 'vertical-align: top',
        vm: 'vertical-align: middle',
        vb: 'vertical-align: bottom',
        poi: 'cursor: pointer',
        def: 'cursor: default',
        tex: 'cursor: text',
        ovh: 'overflow: hidden',
        ova: 'overflow: auto',
        vh: 'visibility: hidden',
        vv: 'visibility: visible',
        prew: 'white-space: pre-wrap',
        pre: 'white-space: pre',
        nowrap: 'white-space: nowrap',
        bk: 'word-break: break-all',
        bkw: 'word-wrap: break-word',
        ws: 'word-spacing: ',
        ls: 'letter-spacing: ',
        a: 'animation: ',
        trm: 'transform: ',
        trs: 'transition: ',
        bs: 'box-shadow: ',
        ts: 'text-shadow: ',
        con: 'content: ',
        table: 'display: table; table-layout: fixed; width: 100%',
        center: 'position: absolute; top: 0; bottom: 0; right: 0; left: 0; margin: auto',
        ell: 'text-overflow: ellipsis; white-space: nowrap; overflow: hidden',
        clip: 'position: absolute; clip: rect(0 0 0 0)'
    },
    valueMap: {
        a: 'auto',
        s: 'solid',
        d: 'dashed',
        tt: 'transparent',
        cc: 'currentColor',
        n: 'normal',
        c: 'center',
        rx: 'repeat-x',
        ry: 'repeat-y',
        no: 'no-repeat',
        ih: 'inherit',
        l: 'left',
        t: 'top',
        r: 'right',
        b: 'bottom'
    }
};